# Generated by Django 4.2.10 on 2026-03-07 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('loan_type', models.CharField(choices=[('personal', 'personal'), ('home', 'home'), ('car', 'car'), ('education', 'education')], default='personal', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenure_months', models.IntegerField(default=12)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('disbursed', 'disbursed'), ('closed', 'closed')], default='pending', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.5, max_digits=5)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
