# Generated by Django 4.2.10 on 2026-03-11 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_userprofile_mpin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_user_id_cf0c2a_idx',
            old_name='bank_acc_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bankaccount',
            new_name='bank_accoun_account_a5c8c7_idx',
            old_name='bank_acc_number_idx',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('fixed', 'Fixed Deposit'), ('recurring', 'Recurring Deposit')], default='savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kycdetail',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
