# Generated by Django 4.2.10 on 2026-03-07 13:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField(blank=True, null=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('prepaid', 'Prepaid')], default='debit', max_length=10)),
                ('network', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('rupay', 'RuPay')], default='visa', max_length=12)),
                ('holder_name', models.CharField(max_length=100)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('cvv_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('is_contactless', models.BooleanField(default=True)),
                ('is_online_enabled', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
