# Generated by Django 4.2.10 on 2026-03-08 04:11

import apps.cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='card',
            name='employment_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='card',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=apps.cards.models.generate_card_number, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
