# Generated by Django 4.2.10 on 2026-03-07 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('from_account', models.CharField(db_index=True, max_length=20)),
                ('to_account', models.CharField(db_index=True, max_length=20)),
                ('from_user_id', models.UUIDField(db_index=True)),
                ('to_user_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('txn_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('mode', models.CharField(choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('atm', 'ATM'), ('pos', 'POS'), ('online', 'Online'), ('emi', 'EMI'), ('other', 'Other')], default='imps', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('flagged', 'Flagged'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='UPIId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('account_id', models.UUIDField()),
                ('vpa', models.CharField(max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'upi_ids',
            },
        ),
        migrations.CreateModel(
            name='UPITransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_vpa', models.CharField(max_length=100)),
                ('to_vpa', models.CharField(max_length=100)),
                ('upi_ref_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_detail', to='txn_transactions.transaction')),
            ],
            options={
                'db_table': 'upi_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_account', 'status'], name='transaction_from_ac_fa4ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_account', 'status'], name='transaction_to_acco_f992de_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_user_id', 'initiated_at'], name='transaction_from_us_bc22dc_idx'),
        ),
    ]
